name: credo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  web3dart: ^2.7.3
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  bip39: ^1.0.6
  google_fonts: ^6.3.1
  hex: ^0.2.0
  bip32: ^2.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/
    - assets/tokens/
    - assets/abi/
